# Generated by Django 4.2.5 on 2024-02-16 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txn_id', models.CharField(max_length=100, verbose_name='Transaction ID')),
                ('timestamp', models.DateTimeField(verbose_name='Timestamp')),
                ('customer_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Customer ID')),
                ('aadhaar_number', models.CharField(max_length=100, verbose_name='Aadhaar Number')),
                ('transaction_type', models.CharField(max_length=100, verbose_name='Transaction Type')),
                ('transaction_amount_value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Transaction Amount Value')),
                ('transaction_amount_currency', models.CharField(max_length=3, verbose_name='Transaction Amount Currency')),
                ('transaction_status', models.CharField(blank=True, max_length=100, null=True, verbose_name='Transaction Status')),
                ('error_code', models.CharField(blank=True, max_length=100, null=True, verbose_name='Error Code')),
                ('merchant_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Merchant ID')),
                ('terminal_id', models.CharField(max_length=100, verbose_name='Terminal ID')),
                ('bank_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Bank ID')),
                ('location', models.CharField(max_length=100, verbose_name='Location')),
                ('transaction_ref_number', models.CharField(max_length=100, verbose_name='Transaction Reference Number')),
                ('response_code', models.CharField(blank=True, max_length=100, null=True, verbose_name='Response Code')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='Remarks')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='User Agent')),
                ('transaction_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Transaction Fee')),
            ],
        ),
    ]
