# Generated by Django 4.2.5 on 2024-02-19 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('withdrawreqDB', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='customer_reference_number',
            field=models.CharField(max_length=100, null=True, verbose_name='Customer Reference Number'),
        ),
    ]
